### PR TITLE
Updated ValueSet for DocumentReference.Type

### PR DESCRIPTION
**Pull request by kennethmyhra**
* NoBasisDocumentReferenceType now uses codes from Volven 9602

### CODE REVIEW

**Comment by oaassv** [comment]
Ser fint ut Kenneth,har du også fjernet referansen til ClinicalNote for Category?


øyvind
    På mandag 5. oktober 2020, 20:36:48 CEST skrev Kenneth Myhra <notifications@github.com> følgende:  
 
 


@kennethmyhra requested your review on: #53 Updated ValueSet for DocumentReference.Type.

**Comment by kennethmyhra** [comment]
OK, done

**Review by thomiz — APPROVED** [review]

**Review by rockphotog — APPROVED** [review]

**Comment by thomiz** [comment]
Removed reference to no-basis-documentreference-category ValueSet that no longer exists

**Review by thomiz — APPROVED** [review]
Tok bort  no-basis-Composition.structuredefinition/no-basis-
 <element id="Composition.category">
      <path value="Composition.category" />
      <binding>
        <strength value="required" />
        <valueSet value="http://hl7.no/fhir/ValueSet/no-basis-documentreference-category" />
      </binding>
    </element>

**Review by oaassv — APPROVED** [review]

**Pull request merged**
